### ISSUE TITLE
Find Largest element in an array

### ISSUE THREAD

**Issue by Nikhil-2002** [Nikhil-2002/Programming_Hactoberfest23#1]

**Comment by SRUJANA2199** [comment]
hi could you assign me this issue  ?

**Comment by Nikhil-2002** [comment]
@SRUJANA2199 assigned..

**Comment by jeniljain2811** [comment]
@Nikhil-2002 I am interested to solve this problem . Can you pls assign it to me if it is available?

**Comment by SRUJANA2199** [comment]
hi could you please add hacktoberfest 23 tags which are required because these ones are not being accepted in the competetion

**Comment by Kedarnath-Rothe** [comment]
Please assign me this task

**Comment by Subrat29** [comment]
Hey @Nikhil-2002 ,
I'd like to work on this issue. Could you please assign it to me?

Thank you,
Subrat
