### ISSUE TITLE
Finding Arrays are disjoint or not 

### ISSUE THREAD

**Issue by Nikhil-2002** [Nikhil-2002/Programming_Hactoberfest23#10]

**Comment by Mahesh0911** [comment]
I'm interested in working on this issue; please consider assigning it to me.

**Comment by Nikhil-2002** [comment]
Sure, I assigned you.

**Comment by Sam-bhav-20** [comment]
hey @Nikhil-2002  

I am working on this issue

**Comment by Chiragchandel2000** [comment]
Hi, i am willing to solve this issue. please assign it to me.
