### ISSUE TITLE
Find Smallest Element in an Array

### ISSUE THREAD

**Issue by Nikhil-2002** [Nikhil-2002/Programming_Hactoberfest23#2]

**Comment by SRUJANA2199** [comment]
hi could you assign me this issue?

**Comment by Piyush-Gambhir** [comment]
Please assign this issue to me.

**Comment by pr1shaaa** [comment]
Hi @Nikhil-2002 - I would like to work on this in python. Kindly assign it to me.

**Comment by Nikhil-2002** [comment]
@pr1shaaa Create python folder first then start contributing

**Comment by aarth01** [comment]
@Nikhil-2002 can you please assign this issue to me! also can i use c or java to solve

**Comment by guru-divine** [comment]
Hi @Nikhil-2002 I want to contribute. Kindly assign this to me. Thanks.

**Comment by Kedarnath-Rothe** [comment]
Please assign me this task

**Comment by Zohaib-4** [comment]
Kindly assign me this issue as I am a beginner in open source contributions and want to start from somewhere but have good knowledge of programming mainly in C++.

**Comment by Subrat29** [comment]
Hey @Nikhil-2002 ,
I'd like to work on this issue. Could you please assign it to me?

Thank you,
Subrat

**Comment by SanskrutiKulkarni** [comment]
Hello @Nikhil-2002 I would like to contribute in this issue
Can you please assign this task to me
