### ISSUE TITLE
Add Kadane's Algorithm in C++

### ISSUE THREAD

**Issue by blindaks** [Nikhil-2002/Programming_Hactoberfest23#24]
Kadane's algorithm is a dynamic programming approach used to solve the maximum subarray problem, which involves finding the contiguous subarray with the maximum sum in an array of numbers.

Please assign this issue to me under Hacktoberfest.

**Comment by blindaks** [comment]
Please add hacktoberfest tags.

**Comment by AnkitaGupta2002** [comment]
Hey, I want to contribute in this.!!

**Comment by ombhagwat2401** [comment]
@Nikhil-2002 I want to contribute on this, please assign me this issue!

**Comment by Kedarnath-Rothe** [comment]
Please assign me this task

**Comment by Subrat29** [comment]
Hello @Nikhil-2002 ,

I'd like to work on this issue. Could you please assign it to me?

Thank you,
Subrat
