### ISSUE TITLE
Implement novel Data Structures like Trie and Disjoint Set Union(DSU) in C++

### ISSUE THREAD

**Issue by FardeenCODEIIEST** [Nikhil-2002/Programming_Hactoberfest23#30]
The repo does not contain the implementation of novel data structures like Trie and Disjoint Set Union, which are used to solve problems related to prefix strings, connectivity and many more in an optimized way.

 I would like to get assigned for this issue.

**Comment by Yash493** [comment]
Please Assign me this issue I have good Knowledge in C++ Programming lanaguge

**Comment by FardeenCODEIIEST** [comment]
Hey @Nikhil-2002 I have successfully fixed the issue, can you please accept the PR under the label 'hacktoberfest'.
