### ISSUE TITLE
Reverse an Array

### ISSUE THREAD

**Issue by Nikhil-2002** [Nikhil-2002/Programming_Hactoberfest23#4]

**Comment by Shivansh175** [comment]
Please assign me this issue..

**Comment by Yash493** [comment]
Hey can u Please assign me this Issue , I have good knowledge about data structures and algorithms

**Comment by dikshant182004** [comment]
hii @Nikhil-2002  .plz assign this issue to me.

**Comment by pr1shaaa** [comment]
Hi @Nikhil-2002 - I would like to work on this in python. Kindly assign it to me.

**Comment by Nikhil-2002** [comment]
you have to make another folder for python

**Comment by Kedarnath-Rothe** [comment]
Please assign me this task

**Comment by Subrat29** [comment]
Hey @Nikhil-2002 ,
I'd like to work on this issue. Could you please assign it to me?

Thank you,
Subrat
