### ISSUE TITLE
Palindrome Checker

### ISSUE THREAD

**Issue by krutika-ladani** [Nikhil-2002/Programming_Hactoberfest23#51]
I would like to add a code to check Palindrome strings in Java.

Please assign me this issue @Nikhil-2002 .
HACTOBERFEST2023

**Comment by NickSahu** [comment]
Hello @Nikhil-2002 I would like to contribute in this issue 
Can you please assign me this task ??

**Comment by VishnuAmit** [comment]
hey @Nikhil-2002 . Kindly assign this to me .

**Comment by Palak4620** [comment]
I would like to contribute to this issue. kindly assign it to me.

**Comment by ishita3513** [comment]
Hey @Nikhil-2002 can I create a new issue and you can assign it under [Programming_Hactoberfest23](https://github.com/Nikhil-2002/Programming_Hactoberfest23)? I am a newbie to open source contribution, I want to contribute.

**Comment by SanskrutiKulkarni** [comment]
Hello @Nikhil-2002 I would like to contribute in this issue
Can you please assign the task to me
