### ISSUE TITLE
Check if a number is an Armstrong Number 

### ISSUE THREAD

**Issue by naikmubashir** [Nikhil-2002/Programming_Hactoberfest23#56]
A number is an Armstrong number if the sum of its own digits raised to the power number of digits gives the number itself.
For example,371 is a three digit Armstrong number  =>  371 = 3^3 + 7^3 + 1^3
For example, 1634 is a four digit Armstrong number  =>  1634 = 1^4 + 6^4 + 3^4 + 4^4

**Comment by naikmubashir** [comment]
I would like to take this issue and solve it.

**Comment by Gaurav-152** [comment]
solve kru?

**Comment by sowmyasri-Z** [comment]
could you please assign me this issue.
