### ISSUE TITLE
Sort the elements of an array

### ISSUE THREAD

**Issue by Nikhil-2002** [Nikhil-2002/Programming_Hactoberfest23#6]

**Comment by Piyush-Gambhir** [comment]
Please assign this issue to me.

**Comment by Yash493** [comment]
Hey can  u please assign me this issue !, I have great knowledge about Data structures and algorithms and i can provide solution in Java,C++,Python with output

**Comment by dikshant182004** [comment]
hii @Nikhil-2002 can u plz assign this issue to me as it seems the perfect match for my first contribution

**Comment by Nikhil-2002** [comment]
@pr1shaaa create another folder for python and start contributing

**Comment by Kedarnath-Rothe** [comment]
Please assign me this task

**Comment by Zohaib-4** [comment]
Kindly assign me this issue as I am a beginner in open source contributions and want to start from somewhere but have good knowledge of programming.

**Comment by Subrat29** [comment]
Hey @Nikhil-2002 ,
I'd like to work on this issue. Could you please assign it to me?

Thank you,
Subrat

**Comment by SanskrutiKulkarni** [comment]
Please assign this issue to me.
